services:
  - type: web
    name: bfhl-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health